Update run script

diff --git a/.github/workflows/compose-instrumented-tests.yml b/.github/workflows/compose-instrumented-tests.yml
--- a/.github/workflows/compose-instrumented-tests.yml
+++ b/.github/workflows/compose-instrumented-tests.yml
@@ -40,12 +40,44 @@ jobs:
 
       - name: Get iOS Simulator UDID
         id: get-simulator-udid
-        uses: ./.github/actions/find-simulator
+        shell: bash
+        run: |
+          DEVICE_NAME="iPhone 14"
+          DEVICE_VERSION="16.1"
+          
+          DEVICE_DASH="${DEVICE_VERSION//./-}"   # 16.0 -> 16-0
+          
+          echo "Looking for device: '$DEVICE_NAME' ($DEVICE_VERSION)"
+          
+          SIMULATOR_ID=$(xcrun simctl list devices available -j \
+          | jq -r --arg device "$DEVICE_NAME" --arg vdot "$DEVICE_VERSION" --arg vdash "$DEVICE_DASH" '
+          .devices
+          | to_entries[]
+          | select(.key | (contains($vdot) or contains($vdash)))
+          | .value[]
+          | select(.name == $device)
+          | .udid
+          ' | head -n 1)
+          
+          if [ -z "$SIMULATOR_ID" ]; then
+          echo "Simulator not found for $DEVICE_NAME ($DEVICE_VERSION)"
+          echo "Available runtimes and matching devices:"
+          xcrun simctl list devices available -j | jq -r '
+          .devices | to_entries[] | "\(.key):\n  " + ( [.value[] | "\(.name) \(.udid) \(.state)"] | join("\n  ") )
+          '
+          exit 1
+          fi
+          
+          echo "Found simulator ID: $SIMULATOR_ID"
+          
+          # make available to later steps and other jobs if needed
+          echo "SIMULATOR_ID=$SIMULATOR_ID" >> "$GITHUB_ENV"
+          echo "simulator-id=$SIMULATOR_ID" >> "$GITHUB_OUTPUT"
 
       - name: Configure Simulator
         run: |
           # Boot a test simulator
-          xcrun simctl boot "$SIMULATOR_ID"
+          xcrun simctl boot "${{ steps.get-simulator-udid.outputs.simulator-id }}"
 
           # Write the accessibility flags inside the Simulator:
           xcrun simctl spawn booted defaults write com.apple.Accessibility AccessibilityEnabled -bool true
@@ -64,7 +96,7 @@ jobs:
           xcodebuild test \
             -scheme Launcher \
             -project Launcher.xcodeproj \
-            -destination 'platform=iOS Simulator,id="$SIMULATOR_ID"'
+            -destination 'platform=iOS Simulator,id=${{ steps.get-simulator-udid.outputs.simulator-id }}'
 
       - name: Test Summary
         uses: test-summary/action@v2
